version: "3.8"

services:
  service_node_js:
    build: ./service_node_js
    ports:
      - "7000:7000"
    environment:
      - PGUSER=postgres
      - PGPASSWORD=pass
      - PGDATABASE=mydb
      - PGHOST=db
      - PGPORT=5432
    depends_on:
      - db

  service_python:
    build: ./service_python
    ports:
      - "7001:7001"
    environment:
      - PGUSER=postgres
      - PGPASSWORD=pass
      - PGDATABASE=mydb
      - PGHOST=db2
      - PGPORT=5432
    depends_on:
      - db2

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    # dépend peut-être des services API
    depends_on:
      - service_node_js
      - service_python

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    volumes:
      - pgdata1:/var/lib/postgresql/data

  db2:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    volumes:
      - pgdata2:/var/lib/postgresql/data

volumes:
  pgdata1:
  pgdata2: