apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata2-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: default  # adapte selon ton cluster
    