apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: db2
  name: db2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db2
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: db2
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: mydb
        - name: POSTGRES_PASSWORD
          value: pass
        - name: POSTGRES_USER
          value: postgres
        image: postgres:15
        imagePullPolicy: ""
        name: db2
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pgdata2
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: pgdata2
        persistentVolumeClaim:
          claimName: pgdata2
status: {}
