apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: service-node-js
  name: service-node-js
spec:
  ports:
  - name: "7000"
    port: 7000
    targetPort: 7000
  selector:
    io.kompose.service: service-node-js
status:
  loadBalancer: {}
