name: Build and Push to Docker Hub

on: [push]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_services: ${{ steps.detect.outputs.services }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2  # Permet git diff

    - name: Detect modified services
      id: detect
      run: |
        SERVICES=$(git diff --name-only HEAD~1 HEAD | grep -oP '(?<=^)(frontend|python-service|node-service)(?=\/)' | sort | uniq)
        echo "Services modifies : ${SERVICES:-aucun}"
        echo "services=${SERVICES:-none}" >> $GITHUB_OUTPUT

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build each service
      run: |
        for service in ${{ needs.detect-changes.outputs.changed_services }}; do
            echo $service
            docker build -t djgitdev/$service:latest ./$service
            docker push djgitdev/$service:latest
        done
      shell: bash
