name: Deploy to Azure VM

on:
  push:
    branches:
      - master  # ou ta branche de production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 20.55.41.167 >> ~/.ssh/known_hosts
        ssh -o ConnectTimeout=10 -i ~/.ssh/ma-cle-azure djawadAzureUser@20.55.41.167 "echo connexion OK"



    - name: Create archive
      run: |
        cd ..
        ls -la
        tar --exclude=microservices.tar.gz -czf microservices.tar.gz MicroservicesDocker

    - name: Copy archive to VM
      run: |
        cd ..
        ls -la
        scp microservices.tar.gz djawadAzureUser@20.55.41.167:~/microservices.tar.gz

    - name: Déploiement sur la VM
  run: |
    ssh -i ~/.ssh/id_rsa djawadAzureUser@20.55.41.167 << 'EOF'
      mkdir -p ~/deploy_directory
      tar -xzf ~/microservices.tar.gz -C ~/deploy_directory
      cd ~/deploy_directory/microservicesdocker

      # Utiliser la bonne commande pour Docker Compose (avec ou sans tiret)
      if command -v docker-compose &> /dev/null; then
        docker-compose up -d --build
      else
        docker compose up -d --build
      fi
    EOF
